/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef  _apache_thrift_frozen_schema_frozen_REFLECTION_H
#define  _apache_thrift_frozen_schema_frozen_REFLECTION_H

namespace apache { namespace thrift { namespace reflection {
class Schema;
}}}

namespace apache { namespace thrift { namespace frozen { namespace schema { namespace frozen_reflection_ {

void reflectionInitializer_2361056240366028172(::apache::thrift::reflection::Schema& schema);

void reflectionInitializer_3221448234020655692(::apache::thrift::reflection::Schema& schema);

void reflectionInitializer_6060681111115730220(::apache::thrift::reflection::Schema& schema);

}}}}} // namespace

#endif
