/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "frozen_constants.h"

namespace apache { namespace thrift { namespace frozen { namespace schema {

const frozenConstants g_frozen_constants;

frozenConstants::frozenConstants() {
  kCurrentFrozenFileVersion = 1;
}

}}}} // namespace

