/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef  _apache_thrift_frozen_schema_frozen_CONSTANTS_H
#define  _apache_thrift_frozen_schema_frozen_CONSTANTS_H

#include "frozen_types.h"

namespace apache { namespace thrift { namespace frozen { namespace schema {

class frozenConstants {
 public:
  frozenConstants();

  int32_t kCurrentFrozenFileVersion;
};

extern const frozenConstants g_frozen_constants;

}}}} // namespace

#endif
