/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "reflection_constants.h"

namespace apache { namespace thrift { namespace reflection {

const reflectionConstants g_reflection_constants;

reflectionConstants::reflectionConstants() {
}

}}} // namespace

