/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef  _apache_thrift_reflection_reflection_REFLECTION_H
#define  _apache_thrift_reflection_reflection_REFLECTION_H

namespace apache { namespace thrift { namespace reflection {
class Schema;
}}}

namespace apache { namespace thrift { namespace reflection { namespace reflection_reflection_ {

void reflectionInitializer_214309804125196972(::apache::thrift::reflection::Schema& schema);

void reflectionInitializer_4733295045172396908(::apache::thrift::reflection::Schema& schema);

void reflectionInitializer_6902704939566307148(::apache::thrift::reflection::Schema& schema);

}}}} // namespace

#endif
