/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef  _apache_thrift_reflection_reflection_CONSTANTS_H
#define  _apache_thrift_reflection_reflection_CONSTANTS_H

#include "reflection_types.h"

namespace apache { namespace thrift { namespace reflection {

class reflectionConstants {
 public:
  reflectionConstants();

};

extern const reflectionConstants g_reflection_constants;

}}} // namespace

#endif
