/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Sasl_constants.h"

namespace apache { namespace thrift { namespace sasl {

const SaslConstants g_Sasl_constants;

}}} // apache::thrift::sasl