/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include "Sasl_types.h"
namespace apache { namespace thrift { namespace sasl {

class SaslConstants {
 public:
  SaslConstants() {}
};

extern const SaslConstants g_Sasl_constants;

}}} // apache::thrift::sasl