cc_library(
  name = 'thrift',
  srcs = [
    'gen-cpp/frozen_constants.cpp',
    'gen-cpp/frozen_reflection.cpp',
    'gen-cpp/frozen_types.cpp',
    'gen-cpp/reflection_constants.cpp',
    'gen-cpp/reflection_reflection.cpp',
    'gen-cpp/reflection_types.cpp'
  ],
  deps = [
    '//fbthrift/thrift/lib/cpp2:cpp2',
  ]
)
